cocoffee/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

core/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    ProductView,
    HomeView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    AboutView,
    ConfirmationView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('about/', AboutView.as_view(), name="about"),
    path('order-confirmation/<pk>/', ConfirmationView.as_view(), name="order-confirmation")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Djanggo Ecommerce</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href=" {% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
        <strong class="blue-text">MDB</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          
         
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link waves-effect">
                <span class="badge red z-depth-1 mr-1"> 1 </span>
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>
            </li>
            <li class="nav-item">
                 <a class="nav-link waves-effect">
                Hi {{ user.username }}!
                </a>
            </li>
             </li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'logout' %}"> logout</a>
            </li>
            {% else %}
             </li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'login' %}"> login</a>
            </li>
            {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

    {% block content %}
    {% endblock content %}

    {% include "footer.html" %}


    {% include "script.html" %}

    {% block extra_script %}
    {% endblock extra_script %}

</body>

</html>

templates/checkout-bk.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

<main >
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.country }}
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>
             
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

          <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.item_name }}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
              </div>
              <span class="text-muted">{{ order_item.get_final_price }}</span>
            </li>
            {% endfor %}
           

            {% comment %} <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$0</span>
            </li> {% endcomment %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>{{ order.get_total_price }}</strong>
            </li>
          </ul>
          <!-- Cart -->

        </div>

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/order_summary-bk.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Your Cart</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.item_name }}</td>
            <td>
            {% if order_item.item.discount_price %}
                <del>${{ order_item.item.price}}</del> 
                ${{ order_item.item.discount_price }}
            {% else %}
                ${{ order_item.item.price}}
            {% endif %}

            </td>
            <td>
                <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_discount_item_price }} 
                <span class="badge badge-success" >Saved ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price}}
            {% endif %}
             <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>

            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">Your Cart Empity</td>
        </tr>

         <tr>
            <td colspan="5">
                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>

        {% endfor %}

        {% if object.get_total_price %}
        <tr>
            <td colspan="4"><b>Total Order Price</b></td>
            <td>${{ object.get_total_price }}</td>
        </tr>
         <tr>
            <td colspan="5">
                <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>
                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>
        
        {% endif %}
        
        </tbody>
    </table>

        </div>
    </div>
</main>

{% endblock content %}

templates/order_summary.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Kaffen - Cafe & Restaurant HTML Template</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="HandheldFriendly" content="true">
	
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Merienda:wght@400;700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
	
	<!-- BEGIN CSS STYLES -->
	<link rel="stylesheet" href="{% static 'template/styles/bootstrap.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/fonts/font-awesome/css/font-awesome.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/fonts/font-awesome/css/line-awesome.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/styles/animate.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/styles/magnific-popup.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/styles/splitting.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/styles/swiper.css' %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'template/style.css' %}" type="text/css" media="all" />
	<!-- END CSS STYLES -->

</head>

<body>
	<div class="bg">

		<!-- Preloader -->
		<div class="preloader">
			<div class="centrize full-width">
				<div class="vertical-center">
					<div class="spinner-logo">
						<img src="{% static 'template/images/logo.png' %}" alt="" />
						<div class="spinner-dot">
							<div class="spinner-line"></div>
						</div>
					</div>
				</div>
			</div>
		</div>

			<!-- Header -->
			<header class="kf-header">
		
				<!-- topline -->
				<div class="kf-topline">
					<div class="row">
						<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
			
							<!-- hours -->
							<div class="kf-h-group">
								<i class="far fa-clock"></i>
								
							</div>
			
						</div>
						<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 align-center">
			
							<!-- social -->
							<div class="kf-h-social">
								<a href="facebook.com" target="blank"><i class="fab fa-facebook-f"></i></a>
								<a href="twitter.com" target="blank"><i class="fab fa-twitter"></i></a>
								<a href="instagram.com" target="blank"><i class="fab fa-instagram"></i></a>
								<a href="youtube.com" target="blank"><i class="fab fa-youtube"></i></a>
							</div>
			
						</div>
						<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 align-right">
			
							<!-- location -->
							<div class="kf-h-group">
								<i class="fas fa-map-marker-alt"></i>
								<em>Location :</em> 5 main street
							</div>
			
						</div>
					</div>
				</div>
			
				<!-- navbar -->
				<div class="kf-navbar">
					<div class="row">
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
			
							<!-- logo -->
							<div class="kf-logo">
								<a href="/"><img src="{% static 'template/images/logo.png' %}" alt="" /></a>
							</div>
			
						</div>
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 align-center">
			
							<!-- main menu -->
							<div class="kf-main-menu">
								<ul>
									<li>
										<a href="/">Home</a>
									</li>
									<li><a href="/about">About</a></li>
									<li>
										<a href="/#store">Store</i></a>
									</li>
									<li>
										<a class="nav-link waves-effect p-1" href="/order-summary">
											<i class="fas fa-shopping-cart" style="font-size: 20px"></i>
										</a>
									</li>
								</ul>
							</div>
			
						</div>
						<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 align-right d-flex">
							<a class="nav-link waves-effect p-1 mt-2 d-md-none" href="/order-summary">
								<i class="fas fa-shopping-cart" style="font-size: 20px; color:white"></i>
							</a>
							<!-- menu btn -->
							<a href="#" class="kf-menu-btn"><span></span></a>
							
						</div>
					</div>
				</div>
			
				<!-- mobile navbar -->
				<div class="kf-navbar-mobile">
			
					<!-- mobile menu -->
					<div class="kf-main-menu">
						<ul>
							<li class="has-children">
								<a href="/">Home</a>
							</li>
							<li><a href="/about">About</a></li>
							<li>
								<a href="/#store">Store</a>
							</li>
						</ul>
					</div>
			
					<!-- mobile topline -->
					<div class="kf-topline">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			
			
							</div>
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			
								<!-- social -->
								<div class="kf-h-social">
									<a href="facebook.com" target="blank"><i class="fab fa-facebook-f"></i></a>
									<a href="twitter.com" target="blank"><i class="fab fa-twitter"></i></a>
									<a href="instagram.com" target="blank"><i class="fab fa-instagram"></i></a>
									<a href="youtube.com" target="blank"><i class="fab fa-youtube"></i></a>
								</div>
			
							</div>
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			
								<!-- hours -->
								<div class="kf-h-group">
									<i class="far fa-clock"></i>
								</div>
			
							</div>
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			
								<!-- location -->
								<div class="kf-h-group">
									<i class="fas fa-map-marker-alt"></i>
									<em>Location :</em> 5 main street
								</div>
			
							</div>
						</div>
					</div>
			
				</div>
			
			</header>

        </div>

        <div class="wrapper">
            <div class="text-center mt-5">
                <h1 class="kf-h-title">Cart</h1>
            </div>
            <div class="row justify-content-center mt-5">
                <div class="col-8" style="background: #090c0f; padding: 30px;">
                    <table class="table" style="color: #7A7A7A">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total Item Price</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.name }}</td>
                            <td>
                            {% if order_item.item.discount_price %}
                                <del>${{ order_item.item.price}}</del> 
                                ${{ order_item.item.discount_price }}
                            {% else %}
                                ${{ order_item.item.price}}
                            {% endif %}
                
                            </td>
                            <td>
                                <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td>
                            {% if order_item.item.discount_price %}
                                ${{ order_item.get_discount_item_price }} 
                                <span class="badge badge-success" >Saved ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                                ${{ order_item.get_total_item_price}}
                            {% endif %}
                             <a style="margin-left:50px" href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                                <i class="fas fa-trash float-right text-danger"></i>
                             </a>
                
                            </td>
                        </tr>
                
                        {% empty %}
                        <tr>
                            <td colspan="5">Your Cart is Empty</td>
                        </tr>
                
                        {% endfor %}
                
                        {% if object.get_total_price %}

                        <tr>
                            <td colspan="4"><b>Total Order Price</b></td>
                            <td>${{ object.get_total_price }}</td>
                        </tr>
                        
                        {% endif %}
                        
                        </tbody>
                    </table>
                </div>
                
            </div>

            <div class="row mt-5 justify-content-center">
                <div class="col-6 d-flex justify-content-around">
                    <a href="{% url 'core:checkout' %}" class="kf-btn h-btn">
                        <span>Checkout</span>
                    </a>
                    <a href="/" class="kf-btn h-btn">
                        <span>Continue Shopping</span>
                    </a>
                </div>
            </div> 
        </div>


        <!-- Scripts -->
        <script src="{% static 'template/js/jquery.min.js' %}"></script>
        <script src="{% static 'template/js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'template/js/bootstrap.js' %}"></script>
        <script src="{% static 'template/js/swiper.js' %}"></script>
        <script src="{% static 'template/js/splitting.js' %}"></script>
        <script src="{% static 'template/js/jquery.paroller.min.js' %}"></script>
        <script src="{% static 'template/js/parallax.js' %}"></script>
        <script src="{% static 'template/js/magnific-popup.js' %}"></script>
        <script src="{% static 'template/js/imagesloaded.pkgd.js' %}"></script>
        <script src="{% static 'template/js/isotope.pkgd.js' %}"></script>
        <script src="{% static 'template/js/jquery.scrolla.js' %}"></script>
        <script src="{% static 'template/js/skrollr.js' %}"></script>
        <script src="{% static 'template/js/common.js' %}"></script>

    </body>
</html>
        

templates/product-bk.html
{% extends 'base.html' %}

{% block content %}

<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">{{ object.get_label_display }}</span>
              </a>
            </div>

            <p class="lead">

            {% if object.discount_price %}
              <span class="mr-1">
              <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
            {% else %}
             <span>${{ object.price }}</span>
            {% endif %}

            </p>

            <p class="lead font-weight-bold">{{ object.item_name }}</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            {{ object.get_quantity_in_chart }}
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >Remove From cart
                <i class="fas fa-trash ml-1"></i>
            </a>
           

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/script.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
// Animations initialization
new WOW().init();

</script>